const qualities = {
  qualities: [
    "Accomplished",
    "Accurate",
    "Active",
    "Adaptable",
    "Adventurous",
    "Ambitious",
    "Analytical",
    "Articulate",
    "Assertive",
    "Attentive",
    "Calm",
    "Capable",
    //   "Compassionate",
    "Competent",
    "Competitive",
    //   "Concise",
    "Confident",
    "Conscientious",
    "Considerate",
    "Consistent",
    "Constructive",
    "Creative",
    "Decisive",
    "Dependable",
    "Determined",
    "Diligent",
    "Disciplined",
    "Eager",
    "Economical",
    "Effective",
    "Efficient",
    "Empathetic",
    "Encouraging",
    "Energetic",
    "Enterprising",
    "Enthusiastic",
    //   "Ethical",
    "Flexible",
    "Focused",
    "Friendly",
    //   "Formal",
    "Goal orientated",
    "Hard working",
    "Innovative",
    "Insightful",
    "Intellectual",
    "Intelligent",
    "Logical",
    "Mature",
    "Methodical",
    "Meticulous",
    "Motivated",
    "Natural ability",
    "Observant",
    "Optimistic",
    "Organised",
    "Original",
    "Patient",
    "Perceptive",
    "Persistent",
    "Persuasive",
    "Positive",
    "Practical",
    "Precise",
    "Productive",
    "Prudent",
    "Qualified",
    "Quick",
    //   "Rational",
    //   "Realistic",
    //   "Reflective",
    "Reliable",
    "Resourceful",
    "Responsible",
    "Responsive",
    "Self-assured",
    "Self-confident",
    //   "Self-controlled",
    "Self-reliant",
    "Self-starting",
    "Sincere",
    "Strong",
    "Sympathetic",
    "Systematic",
    "Tactful",
    "Talented",
    "Tenacious",
    "Thorough",
    "Versatile",
    //   "Wise",
  ],
};
